#! /bin/bash
# power adjustments for maximum battery life on ASUS U36SD notebook
# crysman(c)2011-10

echo ">>This script is originally written for ASUS U36SD notebooks, using kernel 3.0.0-12."
echo ">>I highly reccommend to boot with i915.i915_enable_rc6=1 option, it saves a lot of Watts and puts system temperature back to normal level (50°) as with 2.6.38-12 kernel."
echo ">>You need acpi_call installed somewhere and edit the path to it in this script."
sudo echo "--"

#------------------------------------- variables()
#modify here, no slash at the end
ACPI_CALL_DIR='/home/abonec/repos/other/acpi_call'
NTPSERVER='ntp.ubuntu.com'

#------------------------------------- functions()
function OK() {
	if [ "$1" != "" ]; then 	
		echo -e "\e[1;32m  OK\e[0m ($1)"
	else
		echo -e "\e[1;32m  OK\e[0m"
	fi
}

function ERR(){
	if [ "$1" != "" ]; then
		echo -e "\e[1;31m  FAIL\e[0m ($1)"
	else
		echo -e "\e[1;31m  FAIL\e[0m"
	fi
}

function showexitstatus(){
#do not add any command before the if statement!
  if [ $? -eq 0 ]; then
    OK
  else
    ERR
  fi
}

#--------------------------------- main()
#laptop_mode
echo ">>checking if laptop_mode is activated..."
if [ `cat /proc/sys/vm/laptop_mode` -eq 5 ]; then
	OK "already set to 5, nothing to do here"
else
	ERR "not activated, setting it to 5..."
	sudo sh -c 'echo 5 > /proc/sys/vm/laptop_mode'
	showexitstatus
fi

#audio
#mute
#TODO buggy!! see powertop
#echo ">>muting sound..."
#amixer set Master mute > /dev/null
#showexitstatus

echo ">>enabling power savings for sound card..."
sudo sh -c 'echo Y > /sys/module/snd_hda_intel/parameters/power_save_controller'
sudo sh -c 'echo 1 > /sys/module/snd_hda_intel/parameters/power_save'
showexitstatus

#LCD brightness
echo ">>setting brightness level to 1..."
sudo sh -c 'for i in /sys/class/backlight/acpi_video*/brightness; do echo -n 1 > $i; done'
showexitstatus

#dedicated graphic card
echo ">>switching off the Nvidia dedicated card..."
if lsmod | grep '^acpi_call' > /dev/null; then
	OK "acpi_call.ko already present in kernel, not inserting"
else
	echo "  >>inserting acpi_call.ko into kernel"	
	sudo insmod $ACPI_CALL_DIR/acpi_call.ko
	showexitstatus
fi
sudo $ACPI_CALL_DIR/test_off.sh
showexitstatus

#CPU
# Select Ondemand CPU Governor
echo ">>activating ondemand CPU governor"
sudo sh -c 'for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo ondemand > $i; done'
showexitstatus

#multi-threading scheduler tunable
echo ">>enabling multi-threading sheduler"
sudo sh -c "echo 1 > /sys/devices/system/cpu/sched_mc_power_savings"
showexitstatus

#harddisk tweaks
echo ">>setting up the SATA link Power management to min_power..."
sudo sh -c 'for i in /sys/class/scsi_host/host*/link_power_management_policy; do echo min_power > $i; done'
showexitstatus

echo ">>reducing dirty page (VM) writebacks to 1500cs..."
sudo sh -c 'echo 1500 > /proc/sys/vm/dirty_writeback_centisecs'
showexitstatus

#autosuspend devices
echo ">>setting up USB auto power levels..."
sudo sh -c 'for i in /sys/bus/usb/devices/*/power/level; do echo auto > $i; done'
showexitstatus

echo ">>setting up autosuspend for USB devices..."
sudo sh -c 'for i in /sys/bus/usb/devices/*/power/autosuspend; do echo 1 > $i; done'
showexitstatus

echo ">>setting up autosuspend for PCI devices..."
sudo sh -c 'for i in /sys/bus/pci/devices/*/power/control; do echo auto > $i; done'
showexitstatus

#ntpd
echo ">>syncing system time and stopping ntpd..."
sudo service ntp stop
sudo ntpdate $NTPSERVER
showexitstatus

#networking
echo ">>activate wireless power saving mode with 500ms..."
sudo iwconfig wlan0 power timeout 500ms
showexitstatus

echo -e '>>reducing wireless adapter power to 5\n  ("sudo iwconfig wlan0 txpower auto" to revert) ...'
sudo iwconfig wlan0 txpower 5
showexitstatus

echo ">>disabling wake-on-LAN..."
sudo ethtool -s eth0 wol d
showexitstatus

#bluetooth
echo '>>switching off bluetooth...'
#sudo ifdown eth1
ERR "not yet implemented :( please, do it manually"
#showexitstatus

echo '>>disabling networking...'
ERR "not yet implemented :( please, do it manually"
#showexitstatus
